image: gitpod/workspace-postgres

ports:
  - port: 5432 #postgres
    onOpen: ignore
  - port: 3000 #http
    onOpen: notify
    visibility: public

tasks:
  - init: >
      cp .env.sample .env &&
      nvm install 16.20.0 &&
      nvm alias default 16.20.0 &&
      npm ci --no-audit --no-progress &&
      npx prisma generate &&
      npx prisma db push &&
      npx prisma db seed &&
      chmod 777 gitpod-instructions.sh
    command: >
      ./gitpod-instructions.sh

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: false

vscode:
  extensions:
    - dbaeumer.vscode-eslint@2.1.8
    - esbenp.prettier-vscode@6.4.0
