name: Update copyright year(s) in license file

on:
  schedule:
    - cron: '0 3 1 1 *' # 03:00 AM on January 1

jobs:
  update-license-year:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: FantasticFiasco/action-update-license-year@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: |
            LICENSE
            README.md
          commitTitle: 'docs: update copyright years'
          prTitle: 'docs: update copyright years'
          prBody: It's that time of the year, let's update LICENSE and README.md
          labels: 'status: waiting review'
